context:
  name: tor
  version: "0.4.8.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://www.torproject.org/dist/${{ name }}-${{ version }}.tar.gz
  sha256: 79b4725e1d4b887b9e68fd09b0d2243777d5ce3cd471e538583bcf6f9d8cdb56

build:
  skip:
    - win
  number: 0
  script:
    - if: osx
      then:
        # config.sub is outdated so we need to regenerate it
        - autoreconf -fiv
    - if: linux
      then:
        # https://gitlab.torproject.org/tpo/core/tor/-/blob/tor-0.4.8.16/src/lib/log/util_bug.h#L56
        - export CPPFLAGS="${CPPFLAGS/-DNDEBUG/}"
        - echo $CPPFLAGS
    - ./configure --prefix="$PREFIX"${{ ' --disable-tool-name-check' if build_platform != target_platform else '' }}
    - make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
    - if: osx
      then:
        - autoconf
        - libtool
        - automake
  host:
    - libevent
    - libscrypt
    - openssl
    - zlib
    - liblzma-devel
    - zstd

tests:
  - script:
      - tor --version
about:
  homepage: https://torproject.org
  summary: Anonymizing overlay network for TCP
  license: BSD-2-Clause AND BSD-3-Clause AND MIT AND NCSA
  license_file: LICENSE
  repository: https://gitlab.torproject.org/tpo/core/tor

extra:
  recipe-maintainers:
    - pavelzw
